# Generated by Django 3.1.1 on 2020-10-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_permission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.IntegerField(choices=[(0, 'read'), (1, 'create'), (2, 'update'), (3, 'delete')]),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='social.role'),
        ),
    ]
