# Generated by Django 3.1.1 on 2020-10-23 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_auto_20201023_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_role_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
