# Generated by Django 3.1.1 on 2020-10-23 20:18

from django.db import migrations


def load_builtin_roles(apps, schema_editor):
    Role = apps.get_model("social", "Role")
    role = Role.objects.create(name="Moderator", custom=False)
    role.save()


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_auto_20201030_1742"),
    ]

    operations = [
        migrations.RunPython(load_builtin_roles),
    ]
