# Generated by Django 3.1.1 on 2020-10-23 20:18

from django.db import migrations


def load_builtin_orgs(apps, schema_editor):
    Organization = apps.get_model("social", "Organization")
    org = Organization.objects.create(name="oso")
    org.save()


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_organization"),
    ]

    operations = [
        migrations.RunPython(load_builtin_orgs),
    ]
