# Generated by Django 3.1.1 on 2020-10-30 21:11

from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.hashers import make_password


def load_seed_users(apps, schema_editor):
    Organization = apps.get_model("social", "Organization")
    oso = Organization.objects.get(name="oso")
    monstersinc = Organization.objects.create(name="monstersinc")
    monstersinc.save()

    Role = apps.get_model("social", "Role")
    role = Role.objects.create(name="Moderator", custom=False, organization=monstersinc)
    role.save()

    User = apps.get_model("social", "User")
    user = User.objects.create(
        username="steve",
        email="steve@osohq.com",
        password=make_password("something123"),
    )
    user.organization = oso
    user.save()

    user = User.objects.create(
        username="dave", email="dave@osohq.com", password=make_password("something123")
    )
    user.organization = oso
    user.save()

    user = User.objects.create(
        username="sully",
        email="sully@monsters.com",
        password=make_password("something123"),
    )
    user.organization = monstersinc
    user.save()

    user = User.objects.create(
        username="mike",
        email="mike@monsters.com",
        password=make_password("something123"),
    )
    user.organization = monstersinc
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0013_auto_20201030_2111"),
    ]

    operations = [
        migrations.RunPython(load_seed_users),
    ]