# Generated by Django 3.1.1 on 2020-10-30 21:11

from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.hashers import make_password


def load_seed_users(apps, schema_editor):
    Organization = apps.get_model("social", "Organization")
    oso = Organization.objects.create(name="oso")
    oso.save()
    monstersinc = Organization.objects.create(name="monstersinc")
    monstersinc.save()

    Role = apps.get_model("social", "Role")
    oso_admin = Role.objects.create(name="Admin", custom=False, organization=oso)
    oso_admin.save()
    monsters_admin = Role.objects.create(
        name="Admin", custom=False, organization=monstersinc
    )
    monsters_admin.save()

    User = apps.get_model("social", "User")
    user = User.objects.create(
        username="steve",
        email="steve@osohq.com",
        password=make_password("something123"),
    )
    user.organization = oso
    user.save()

    user = User.objects.create(
        username="dave", email="dave@osohq.com", password=make_password("something123")
    )
    user.organization = oso
    user.save()

    oso_admin.users.add(user)

    user = User.objects.create(
        username="leina",
        email="leina@osohq.com",
        password=make_password("something123"),
    )
    user.organization = oso
    user.save()

    user = User.objects.create(
        username="sully",
        email="sully@monsters.com",
        password=make_password("something123"),
    )
    user.organization = monstersinc
    user.save()

    user = User.objects.create(
        username="mike",
        email="mike@monsters.com",
        password=make_password("something123"),
    )
    user.organization = monstersinc
    user.save()

    monsters_admin.users.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_seed_users),
    ]